import type { Metadata } from 'next';
import { Inter, Poppins, Work_Sans } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { WidgetProvider } from '@/contexts/WidgetContext';
import { SidebarProvider } from '@/contexts/SidebarContext';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'] });
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});
const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WidgetProvider>
          <SidebarProvider>
            {children}
            <Toaster />
          </SidebarProvider>
        </WidgetProvider>
      </body>
    </html>
  );
}
